In [59]:
import numpy as np
arr1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(arr1)

[ 1  2  3  4  5  6  7  8  9 10]


In [60]:
arr2 = np.array([
    [1, 4, 7],
    [2, 5, 8],
    [3, 6, 9]
])
print(arr2)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [47]:
print(arr1.sum())
print(arr1.mean())
print(arr1.max())

55
5.5
10


In [48]:
print(arr1*2)

[ 2  4  6  8 10 12 14 16 18 20]


In [52]:
arr1[arr1>5] = 0
print(arr1)

[1 2 3 4 5 0 0 0 0 0]


In [61]:

arr3 = np.array([1 ,2 ,3])
print(arr3*arr2,"\n")
print(arr3@arr2)

[[ 1  8 21]
 [ 2 10 24]
 [ 3 12 27]] 

[14 32 50]
